version: '3.7'

services:

  nginx:
    image: nginx:1.17-alpine
    container_name: test-nginx
    restart: unless-stopped
    ports:
      - 5500:80
    volumes:
      # Re-use local composer cache via host-volume
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      # Mount source-code for development
      - ./:/var/www/html
      # Mount config for development
      - ./docker/nginx:/etc/nginx/conf.d:cached
    links:
      - php-fpm
    depends_on:
      - php-fpm
      - db
    networks:
      - test

  php-fpm:
    build: docker/php-fpm
    restart: unless-stopped
    container_name: test-php
    ports:
      - 9000:9000
    volumes:
      - ./:/var/www/html
    links:
      - db
    depends_on:
      - db
    networks:
      - test

  db:
    image: mysql:5.7
    restart: unless-stopped
    ports:
      - 33066:3306
    volumes:
      - ./docker/dump:/docker-entrypoint-initdb.d
      - ./docker/storage/mysql:/var/lib/mysql
    environment:
        MYSQL_DATABASE: 'test'
        MYSQL_ROOT_USER: 'root'
        MYSQL_ALLOW_EMPTY_PASSWORD: "true"
        MYSQL_PASSWORD: 'root'
        MYSQL_ROOT_PASSWORD:
    networks:
      - test


networks:
  test:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.101.0/28
